name: ci
on:
  push:
  pull_request:
  schedule:
  - cron: '0 3 * * *'
jobs:
  test:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 25
            os: ubuntu-latest
          - java: 17
            os: ubuntu-latest
          - java: 17
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-java@v5
      with:
        java-version: ${{matrix.java}}
        distribution: zulu
    - uses: actions/checkout@v6
    - uses: sbt/setup-sbt@af116cce31c00823d3903ce687f9cda3a4f19f1b # v1.2.1
    - if: matrix.os != 'windows-latest'
      run: sbt -v --server scalafmtSbtCheck "+ scalafmtCheckAll"
    - shell: bash
      run: sbt -v --server "+ testFull" "+ publishLocal"
    - shell: bash
      run: rm -rf "$HOME/.ivy2/local" || true
