name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 25
            os: ubuntu-latest
          - java: 17
            os: ubuntu-latest
          - java: 17
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-java@v5
      with:
        java-version: ${{matrix.java}}
        distribution: zulu
    - uses: actions/checkout@v6
    - uses: sbt/setup-sbt@3afe9cf056c5d139bfc46579af1192d77a2f0821 # v1.4.0
    - if: matrix.os != 'windows-latest'
      run: sbt -v --server scalafmtSbtCheck "+ scalafmtCheckAll"
    - shell: bash
      run: sbt -v --server "+ testFull" "+ publishLocal"
    - shell: bash
      run: rm -rf "$HOME/.ivy2/local" || true
