name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  test:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 25
            os: ubuntu-latest
          - java: 17
            os: ubuntu-latest
          - java: 17
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/setup-java@v6
      with:
        java-version: ${{matrix.java}}
        distribution: zulu
    - uses: actions/checkout@v7
    - uses: sbt/setup-sbt@6158cb0903b8ceeae04f830055f3155e1b6a5ad7 # v1.5.11
    - if: matrix.os != 'windows-latest'
      run: sbt -v --server scalafmtSbtCheck "+ scalafmtCheckAll"
    - shell: bash
      run: sbt -v --server "+ testFull" "+ publishLocal"
    - shell: bash
      run: rm -rf "$HOME/.ivy2/local" || true
